
/**
 * Enum for Desinty component type
 * @enum
 */
export enum ComponentType {
    None = 0,
    Profiles = 100,
    VendorReceipts = 101,
    ProfileInventories = 102,
    ProfileCurrencies = 103,
    Characters = 200,
    CharacterInventories = 201,
    CharacterProgressions = 202,
    CharacterRenderData = 203,
    CharacterActivities = 204,
    CharacterEquipment = 205,
    ItemInstances = 300,
    ItemObjectives = 301,
    ItemPerks = 302,
    ItemRenderData = 303,
    ItemStats = 304,
    ItemSockets = 305,
    ItemTalentGrids = 306,
    ItemCommonData = 307,
    ItemPlugStates = 308,
    Vendors = 400,
    VendorCategories = 401,
    VendorSales = 402,
    Kiosks = 500,
}

/**
 * Enum for Destiny acitivity mode type
 * @enum
 */
export enum DestinyActivityModeType {
    None = 0,
    Story = 2,
    Strike = 3,
    Reserved4 = 4,
    AllPvP = 5,
    Patrol = 6,
    AllPvE = 7,
    Reserved9 = 9,
    Control = 10,
    Reserved11 = 11,
    Team = 12,
    Reserved13 = 13,
    Reserved15 = 15,
    Nightfall = 16,
    Heroic = 17,
    AllStrikes = 18,
    Reserved19 = 19,
    Reserved20 = 20,
    Reserved21 = 21,
    Reserved22 = 22,
    Reserved24 = 24,
    Reserved25 = 25,
    Reserved26 = 26,
    Reserved27 = 27,
    Reserved28 = 28,
    Reserved29 = 29,
    Reserved30 = 30,
    Reserved32 = 32,
    Survival = 37,
    Countdown = 38,
    Reserved39 = 39,
    Social = 40,
}

/**
 * Enum for Destiny stats group type
 * @enum
 */
export enum DestinyStatsGroupType {
    None = 0,
    General = 1,
    Weapons = 2,
    Medals = 3,
    ReservedGroups = 100,
    Leadboards = 101,
    Activity = 102,
    UniqueWeapon = 103,
    Internal = 104,
}

/**
 * Enum for the Destiny membership type
 * @enum
 */
export enum MembershipType {
    All = -1,
    Xbox = 1,
    PSN = 2,
    Bungie = 254,
}

/**
 * Enum for Destiny period type
 * @enum
 */
export enum PeriodType {
    None = 0,
    Daily = 1,
    AllTime = 2,
    Activity = 3,
}

/**
 * Enum for different search types
 * @enum
 */
export enum SearchType {
    DestinyInventoryItemDefinition,
}

/**
 * Enum for different stat IDs
 * @enum
 */
export enum StatId {
    ActivitiesClearedabilityKills,
    ActivitiesEntered,
    ActivitiesWon,
    Assists,
    AverageDeathDistance,
    AverageKillDistance,
    AverageLifespan,
    AverageScorePerKill,
    AverageScorePerLife,
    BestSingleGameKills,
    BestSingleGameScore,
    Completed,
    FastestCompletionMsForActivity,
    ActivityCompletions,
    ActivityDeaths,
    ActivityKills,
    ActivitySecondsPlayed,
    ActivityWins,
    ActivityGoalsMissed,
    ActivityCompletedFailures,
    ActivitySpecialActions,
    ActivityBestGoalsHit,
    ActivitySpecialScore,
    ActivityFastestObjectiveCompletionMs,
    ActivityBestSingleGameScore,
    ActivityKillsDeathsRatio,
    ActivityKillsDeathsAssists,
    Deaths,
    Kills,
    KillsDeathsRatio,
    KillsDeathsAssists,
    LbSingleGameKills,
    LbPrecisionKills,
    LbAssists,
    LbDeaths,
    LbKills,
    LbObjectivesCompleted,
    LbSingleGameScore,
    MaximumPowerLevel,
    MedalAbilityDawnbladeAerial,
    MedalAbilityDawnbladeSlam,
    MedalAbilityFlowwalkerMulti,
    MedalAbilityFlowwalkerQuick,
    MedalAbilityGunslingerMulti,
    MedalAbilityGunslingerQuick,
    MedalAbilityJuggernautCombo,
    MedalAbilityJuggernautSlam,
    MedalAbilityNightstalkerLongRange,
    MedalAbilityNightstalkerTetherQuick,
    MedalAbilitySentinelCombo,
    MedalAbilitySentinelWard,
    MedalAbilityStormcallerLandfall,
    MedalAbilityStormcallerMulti,
    MedalAbilitySunbreakerLongRange,
    MedalAbilitySunbreakerMulti,
    MedalAbilityVoidwalkerDistance,
    MedalAbilityVoidwalkerVortex,
    MedalAvenger,
    MedalControlAdvantageHold,
    MedalControlAdvantageStreak,
    MedalControlCaptureAllZones,
    MedalControlMostAdvantage,
    MedalControlPerimeterKill,
    MedalControlPowerPlayWipe,
    MedalCountdownDefense,
    MedalCountdownDefusedLastStand,
    MedalCountdownDefusedMulti,
    MedalCountdownDetonated,
    MedalCountdownPerfect,
    MedalCountdownRoundAllAlive,
    MedalCycle,
    MedalDefeatHunterDodge,
    MedalDefeatTitanBrace,
    MedalDefeatWarlockSigil,
    MedalDefense,
    MedalMatchBlowout,
    MedalMatchComeback,
    MedalMatchMostDamage,
    MedalMatchNeverTrailed,
    MedalMatchOvertime,
    MedalMatchUndefeated,
    MedalMulti2x,
    MedalMulti3x,
    MedalMulti4x,
    MedalMultiEntireTeam,
    MedalPayback,
    MedalQuickStrike,
    MedalStreak10x,
    MedalStreak5x,
    MedalStreakAbsurd,
    MedalStreakCombined,
    MedalStreakShutdown,
    MedalStreakTeam,
    MedalSuperShutdown,
    MedalSupremacyCrestCreditStreak,
    MedalSupremacyFirstCrest,
    MedalSupremacyNeverCollected,
    MedalSupremacyPerfectSecureRate,
    MedalSupremacyRecoverStreak,
    MedalSupremacySecureStreak,
    MedalSurvivalComeback,
    MedalSurvivalKnockout,
    MedalSurvivalQuickWipe,
    MedalSurvivalTeamUndefeated,
    MedalSurvivalUndefeated,
    MedalSurvivalWinLastStand,
    MedalWeaponAuto,
    MedalWeaponFusion,
    MedalWeaponGrenade,
    MedalWeaponHandCannon,
    MedalWeaponPulse,
    MedalWeaponRocket,
    MedalWeaponScout,
    MedalWeaponShotgun,
    MedalWeaponSidearm,
    MedalWeaponSmg,
    MedalWeaponSniper,
    MedalWeaponSword,
    MedalsUnknown,
    AllMedalsScore,
    AllMedalsEarned,
    ObjectivesCompleted,
    PrecisionKills,
    ResurrectionsPerformed,
    ResurrectionsReceived,
    Score,
    SecondsPlayed,
    ActivityDurationSeconds,
    Standing,
    Suicides,
    Team,
    TotalDeathDistance,
    TotalKillDistance,
    WeaponPrecisionKillsAutoRifle,
    WeaponPrecisionKillsFusionRifle,
    WeaponPrecisionKillsGrenade,
    WeaponPrecisionKillsHandCannon,
    WeaponPrecisionKillsMachinegun,
    WeaponPrecisionKillsMelee,
    WeaponPrecisionKillsPulseRifle,
    WeaponPrecisionKillsRocketLauncher,
    WeaponPrecisionKillsScoutRifle,
    WeaponPrecisionKillsShotgun,
    WeaponPrecisionKillsSniper,
    WeaponPrecisionKillsSubmachinegun,
    WeaponPrecisionKillsSuper,
    WeaponPrecisionKillsRelic,
    WeaponPrecisionKillsSideArm,
    WeaponKillsAutoRifle,
    WeaponKillsFusionRifle,
    WeaponKillsGrenade,
    WeaponKillsHandCannon,
    WeaponKillsMachinegun,
    WeaponKillsMelee,
    WeaponKillsPulseRifle,
    WeaponKillsRocketLauncher,
    WeaponKillsScoutRifle,
    WeaponKillsShotgun,
    WeaponKillsSniper,
    WeaponKillsSubmachinegun,
    WeaponKillsSuper,
    WeaponKillsRelic,
    WeaponKillsSideArm,
    WeaponKillsSword,
    WeaponKillsAbility,
    WeaponBestType,
    WeaponKillsPrecisionKillsAutoRifle,
    WeaponKillsPrecisionKillsFusionRifle,
    WeaponKillsPrecisionKillsGrenade,
    WeaponKillsPrecisionKillsHandCannon,
    WeaponKillsPrecisionKillsMachinegun,
    WeaponKillsPrecisionKillsMelee,
    WeaponKillsPrecisionKillsPulseRifle,
    WeaponKillsPrecisionKillsRocketLauncher,
    WeaponKillsPrecisionKillsScoutRifle,
    WeaponKillsPrecisionKillsShotgun,
    WeaponKillsPrecisionKillsSniper,
    WeaponKillsPrecisionKillsSubmachinegun,
    WeaponKillsPrecisionKillsSuper,
    WeaponKillsPrecisionKillsRelic,
    WeaponKillsPrecisionKillsSideArm,
    WinLossRatio,
    UniqueWeaponAssists,
    UniqueWeaponAssistDamage,
    UniqueWeaponKills,
    UniqueWeaponPrecisionKills,
    UniqueWeaponKillsPrecisionKills,
    AllParticipantsCount,
    AllParticipantsScore,
    AllParticipantsTimePlayed,
    ActivityAssists,
    CompletionReason,
    FireteamId,
    LongestKillSpree,
    LongestSingleLife,
    MostPrecisionKills,
    OrbsDropped,
    OrbsGathered,
    StartSeconds,
    TimePlayedSeconds,
    PlayerCount,
    ActivityPrecisionKills,
    PublicEventsCompleted,
    PublicEventsJoined,
    RemainingTimeAfterQuitSeconds,
    TeamScore,
    TotalActivityDurationSeconds,
    DailyMedalsEarned,
    CombatRating,
    LbMostPrecisionKills,
    LbLongestKillSpree,
    LbLongestKillDistance,
    LbFastestCompletionMs,
    LbLongestSingleLife,
    FastestCompletionMs,
    LongestKillDistance,
    HighestCharacterLevel,
    HighestLightLevel,
    HighestSandboxLevel,
    SparksCaptured,
    SlamDunks,
    StyleDunks,
    DunkKills,
    CarrierKills,
    ActivityGatesHit,
    RaceCompletionSeconds,
    GatesHit,
    RaceCompletionMilliseconds,
}
