
/**
 * Enum for Desinty component type
 * @enum
 */
export enum ComponentType {
    None = 0,
    Profiles = 100,
    VendorReceipts = 101,
    ProfileInventories = 102,
    ProfileCurrencies = 103,
    Characters = 200,
    CharacterInventories = 201,
    CharacterProgressions = 202,
    CharacterRenderData = 203,
    CharacterActivities = 204,
    CharacterEquipment = 205,
    ItemInstances = 300,
    ItemObjectives = 301,
    ItemPerks = 302,
    ItemRenderData = 303,
    ItemStats = 304,
    ItemSockets = 305,
    ItemTalentGrids = 306,
    ItemCommonData = 307,
    ItemPlugStates = 308,
    Vendors = 400,
    VendorCategories = 401,
    VendorSales = 402,
    Kiosks = 500,
}

/**
 * Enum for Destiny acitivity mode type
 * @enum
 */
export enum DestinyActivityModeType {
    None = 0,
    Story = 2,
    Strike = 3,
    Reserved4 = 4,
    AllPvP = 5,
    Patrol = 6,
    AllPvE = 7,
    Reserved9 = 9,
    Control = 10,
    Reserved11 = 11,
    Team = 12,
    Reserved13 = 13,
    Reserved15 = 15,
    Nightfall = 16,
    Heroic = 17,
    AllStrikes = 18,
    Reserved19 = 19,
    Reserved20 = 20,
    Reserved21 = 21,
    Reserved22 = 22,
    Reserved24 = 24,
    Reserved25 = 25,
    Reserved26 = 26,
    Reserved27 = 27,
    Reserved28 = 28,
    Reserved29 = 29,
    Reserved30 = 30,
    Reserved32 = 32,
    Survival = 37,
    Countdown = 38,
    Reserved39 = 39,
    Social = 40,
}

/**
 * Enum for Destiny stats group type
 * @enum
 */
export enum DestinyStatsGroupType {
    None = 0,
    General = 1,
    Weapons = 2,
    Medals = 3,
    ReservedGroups = 100,
    Leadboards = 101,
    Activity = 102,
    UniqueWeapon = 103,
    Internal = 104,
}

/**
 * Enum for the Destiny membership type
 * @enum
 */
export enum MembershipType {
    All = -1,
    Xbox = 1,
    PSN = 2,
    Bungie = 254,
}

/**
 * Enum for Destiny period type
 * @enum
 */
export enum PeriodType {
    None = 0,
    Daily = 1,
    AllTime = 2,
    Activity = 3,
}

/**
 * Enum for different search types
 * @enum
 */
export enum SearchType {
    DestinyInventoryItemDefinition = 'DestinyInventoryItemDefinition',
}

/**
 * Enum for different stat IDs
 * @enum
 */
export enum StatId {
    ActivitiesClearedabilityKills = 'DestinyInventoryItemDefinition',
    ActivitiesEntered = 'ActivitiesEntered',
    ActivitiesWon = 'ActivitiesWon',
    Assists = 'Assists',
    AverageDeathDistance = 'AverageDeathDistance',
    AverageKillDistance = 'AverageKillDistance',
    AverageLifespan = 'AverageLifespan',
    AverageScorePerKill = 'AverageScorePerKill',
    AverageScorePerLife = 'AverageScorePerLife',
    BestSingleGameKills = 'BestSingleGameKills',
    BestSingleGameScore = 'BestSingleGameScore',
    Completed = 'Completed',
    FastestCompletionMsForActivity = 'FastestCompletionMsForActivity',
    ActivityCompletions = 'ActivityCompletions',
    ActivityDeaths = 'ActivityDeaths',
    ActivityKills = 'ActivityKills',
    ActivitySecondsPlayed = 'ActivitySecondsPlayed',
    ActivityWins = 'ActivityWins',
    ActivityGoalsMissed = 'ActivityGoalsMissed',
    ActivityCompletedFailures = 'ActivityCompletedFailures',
    ActivitySpecialActions = 'ActivitySpecialActions',
    ActivityBestGoalsHit = 'ActivityBestGoalsHit',
    ActivitySpecialScore = 'ActivitySpecialScore',
    ActivityFastestObjectiveCompletionMs = 'ActivityFastestObjectiveCompletionMs',
    ActivityBestSingleGameScore = 'ActivityBestSingleGameScore',
    ActivityKillsDeathsRatio = 'ActivityKillsDeathsRatio',
    ActivityKillsDeathsAssists = 'ActivityKillsDeathsAssists',
    Deaths = 'Deaths',
    Kills = 'Kills',
    KillsDeathsRatio = 'KillsDeathsRatio',
    KillsDeathsAssists = 'KillsDeathsAssists',
    LbSingleGameKills = 'LbSingleGameKills',
    LbPrecisionKills = 'LbPrecisionKills',
    LbAssists = 'LbAssists',
    LbDeaths = 'LbDeaths',
    LbKills = 'LbKills',
    LbObjectivesCompleted = 'LbObjectivesCompleted',
    LbSingleGameScore = 'LbSingleGameScore',
    MaximumPowerLevel = 'MaximumPowerLevel',
    MedalAbilityDawnbladeAerial = 'MedalAbilityDawnbladeAerial',
    MedalAbilityDawnbladeSlam = 'MedalAbilityDawnbladeSlam',
    MedalAbilityFlowwalkerMulti = 'MedalAbilityFlowwalkerMulti',
    MedalAbilityFlowwalkerQuick = 'MedalAbilityFlowwalkerQuick',
    MedalAbilityGunslingerMulti = 'MedalAbilityGunslingerMulti',
    MedalAbilityGunslingerQuick = 'MedalAbilityGunslingerQuick',
    MedalAbilityJuggernautCombo = 'MedalAbilityJuggernautCombo',
    MedalAbilityJuggernautSlam = 'MedalAbilityJuggernautSlam',
    MedalAbilityNightstalkerLongRange = 'MedalAbilityNightstalkerLongRange',
    MedalAbilityNightstalkerTetherQuick = 'MedalAbilityNightstalkerTetherQuick',
    MedalAbilitySentinelCombo = 'MedalAbilitySentinelCombo',
    MedalAbilitySentinelWard = 'MedalAbilitySentinelWard',
    MedalAbilityStormcallerLandfall = 'MedalAbilityStormcallerLandfall',
    MedalAbilityStormcallerMulti = 'MedalAbilityStormcallerMulti',
    MedalAbilitySunbreakerLongRange = 'MedalAbilitySunbreakerLongRange',
    MedalAbilitySunbreakerMulti = 'MedalAbilitySunbreakerMulti',
    MedalAbilityVoidwalkerDistance = 'MedalAbilityVoidwalkerDistance',
    MedalAbilityVoidwalkerVortex = 'MedalAbilityVoidwalkerVortex',
    MedalAvenger = 'MedalAvenger',
    MedalControlAdvantageHold = 'MedalControlAdvantageHold',
    MedalControlAdvantageStreak = 'MedalControlAdvantageStreak',
    MedalControlCaptureAllZones = 'MedalControlCaptureAllZones',
    MedalControlMostAdvantage = 'MedalControlMostAdvantage',
    MedalControlPerimeterKill = 'MedalControlPerimeterKill',
    MedalControlPowerPlayWipe = 'MedalControlPowerPlayWipe',
    MedalCountdownDefense = 'MedalCountdownDefense',
    MedalCountdownDefusedLastStand = 'MedalCountdownDefusedLastStand',
    MedalCountdownDefusedMulti = 'MedalCountdownDefusedMulti',
    MedalCountdownDetonated = 'MedalCountdownDetonated',
    MedalCountdownPerfect = 'MedalCountdownPerfect',
    MedalCountdownRoundAllAlive = 'MedalCountdownRoundAllAlive',
    MedalCycle = 'MedalCycle',
    MedalDefeatHunterDodge = 'MedalDefeatHunterDodge',
    MedalDefeatTitanBrace = 'MedalDefeatTitanBrace',
    MedalDefeatWarlockSigil = 'MedalDefeatWarlockSigil',
    MedalDefense = 'MedalDefense',
    MedalMatchBlowout = 'MedalMatchBlowout',
    MedalMatchComeback = 'MedalMatchComeback',
    MedalMatchMostDamage = 'MedalMatchMostDamage',
    MedalMatchNeverTrailed = 'MedalMatchNeverTrailed',
    MedalMatchOvertime = 'MedalMatchOvertime',
    MedalMatchUndefeated = 'MedalMatchUndefeated',
    MedalMulti2x = 'MedalMulti2x',
    MedalMulti3x = 'MedalMulti3x',
    MedalMulti4x = 'MedalMulti4x',
    MedalMultiEntireTeam = 'MedalMultiEntireTeam',
    MedalPayback = 'MedalPayback',
    MedalQuickStrike = 'MedalQuickStrike',
    MedalStreak10x = 'MedalStreak10x',
    MedalStreak5x = 'MedalStreak5x',
    MedalStreakAbsurd = 'MedalStreakAbsurd',
    MedalStreakCombined = 'MedalStreakCombined',
    MedalStreakShutdown = 'MedalStreakShutdown',
    MedalStreakTeam = 'MedalStreakTeam',
    MedalSuperShutdown = 'MedalSuperShutdown',
    MedalSupremacyCrestCreditStreak = 'MedalSupremacyCrestCreditStreak',
    MedalSupremacyFirstCrest = 'MedalSupremacyFirstCrest',
    MedalSupremacyNeverCollected = 'MedalSupremacyNeverCollected',
    MedalSupremacyPerfectSecureRate = 'MedalSupremacyPerfectSecureRate',
    MedalSupremacyRecoverStreak = 'MedalSupremacyRecoverStreak',
    MedalSupremacySecureStreak = 'MedalSupremacySecureStreak',
    MedalSurvivalComeback = 'MedalSurvivalComeback',
    MedalSurvivalKnockout = 'MedalSurvivalKnockout',
    MedalSurvivalQuickWipe = 'MedalSurvivalQuickWipe',
    MedalSurvivalTeamUndefeated = 'MedalSurvivalTeamUndefeated',
    MedalSurvivalUndefeated = 'MedalSurvivalUndefeated',
    MedalSurvivalWinLastStand = 'MedalSurvivalWinLastStand',
    MedalWeaponAuto = 'MedalWeaponAuto',
    MedalWeaponFusion = 'MedalWeaponFusion',
    MedalWeaponGrenade = 'MedalWeaponGrenade',
    MedalWeaponHandCannon = 'MedalWeaponHandCannon',
    MedalWeaponPulse = 'MedalWeaponPulse',
    MedalWeaponRocket = 'MedalWeaponRocket',
    MedalWeaponScout = 'MedalWeaponScout',
    MedalWeaponShotgun = 'MedalWeaponShotgun',
    MedalWeaponSidearm = 'MedalWeaponSidearm',
    MedalWeaponSmg = 'MedalWeaponSmg',
    MedalWeaponSniper = 'MedalWeaponSniper',
    MedalWeaponSword = 'MedalWeaponSword',
    MedalsUnknown = 'MedalsUnknown',
    AllMedalsScore = 'AllMedalsScore',
    AllMedalsEarned = 'AllMedalsEarned',
    ObjectivesCompleted = 'ObjectivesCompleted',
    PrecisionKills = 'PrecisionKills',
    ResurrectionsPerformed = 'ResurrectionsPerformed',
    ResurrectionsReceived = 'ResurrectionsReceived',
    Score = 'Score',
    SecondsPlayed = 'SecondsPlayed',
    ActivityDurationSeconds = 'ActivityDurationSeconds',
    Standing = 'ActivityDurationSeconds',
    Suicides = 'Suicides',
    Team = 'Team',
    TotalDeathDistance = 'TotalDeathDistance',
    TotalKillDistance = 'TotalKillDistance',
    WeaponPrecisionKillsAutoRifle = 'WeaponPrecisionKillsAutoRifle',
    WeaponPrecisionKillsFusionRifle = 'WeaponPrecisionKillsFusionRifle',
    WeaponPrecisionKillsGrenade = 'WeaponPrecisionKillsGrenade',
    WeaponPrecisionKillsHandCannon = 'WeaponPrecisionKillsHandCannon',
    WeaponPrecisionKillsMachinegun = 'WeaponPrecisionKillsMachinegun',
    WeaponPrecisionKillsMelee = 'WeaponPrecisionKillsMelee',
    WeaponPrecisionKillsPulseRifle = 'WeaponPrecisionKillsPulseRifle',
    WeaponPrecisionKillsRocketLauncher = 'WeaponPrecisionKillsRocketLauncher',
    WeaponPrecisionKillsScoutRifle = 'WeaponPrecisionKillsScoutRifle',
    WeaponPrecisionKillsShotgun = 'WeaponPrecisionKillsShotgun',
    WeaponPrecisionKillsSniper = 'WeaponPrecisionKillsSniper',
    WeaponPrecisionKillsSubmachinegun = 'WeaponPrecisionKillsSubmachinegun',
    WeaponPrecisionKillsSuper = 'WeaponPrecisionKillsSuper',
    WeaponPrecisionKillsRelic = 'WeaponPrecisionKillsRelic',
    WeaponPrecisionKillsSideArm = 'WeaponPrecisionKillsSideArm',
    WeaponKillsAutoRifle = 'WeaponKillsAutoRifle',
    WeaponKillsFusionRifle = 'WeaponKillsFusionRifle',
    WeaponKillsGrenade = 'WeaponKillsGrenade',
    WeaponKillsHandCannon = 'WeaponKillsHandCannon',
    WeaponKillsMachinegun = 'WeaponKillsMachinegun',
    WeaponKillsMelee = 'WeaponKillsMelee',
    WeaponKillsPulseRifle = 'WeaponKillsPulseRifle',
    WeaponKillsRocketLauncher = 'WeaponKillsRocketLauncher',
    WeaponKillsScoutRifle = 'WeaponKillsScoutRifle',
    WeaponKillsShotgun = 'WeaponKillsShotgun',
    WeaponKillsSniper = 'WeaponKillsSniper',
    WeaponKillsSubmachinegun = 'WeaponKillsSubmachinegun',
    WeaponKillsSuper = 'WeaponKillsSuper',
    WeaponKillsRelic = 'WeaponKillsRelic',
    WeaponKillsSideArm = 'WeaponKillsSideArm',
    WeaponKillsSword = 'WeaponKillsSword',
    WeaponKillsAbility = 'WeaponKillsAbility',
    WeaponBestType = 'WeaponBestType',
    WeaponKillsPrecisionKillsAutoRifle = 'WeaponKillsPrecisionKillsAutoRifle',
    WeaponKillsPrecisionKillsFusionRifle = 'WeaponKillsPrecisionKillsFusionRifle',
    WeaponKillsPrecisionKillsGrenade = 'WeaponKillsPrecisionKillsGrenade',
    WeaponKillsPrecisionKillsHandCannon = 'WeaponKillsPrecisionKillsHandCannon',
    WeaponKillsPrecisionKillsMachinegun = 'WeaponKillsPrecisionKillsMachinegun',
    WeaponKillsPrecisionKillsMelee = 'WeaponKillsPrecisionKillsMelee',
    WeaponKillsPrecisionKillsPulseRifle = 'WeaponKillsPrecisionKillsPulseRifle',
    WeaponKillsPrecisionKillsRocketLauncher = 'WeaponKillsPrecisionKillsRocketLauncher',
    WeaponKillsPrecisionKillsScoutRifle = 'WeaponKillsPrecisionKillsScoutRifle',
    WeaponKillsPrecisionKillsShotgun = 'WeaponKillsPrecisionKillsShotgun',
    WeaponKillsPrecisionKillsSniper = 'WeaponKillsPrecisionKillsSniper',
    WeaponKillsPrecisionKillsSubmachinegun = 'WeaponKillsPrecisionKillsSubmachinegun',
    WeaponKillsPrecisionKillsSuper = 'WeaponKillsPrecisionKillsSuper',
    WeaponKillsPrecisionKillsRelic = 'WeaponKillsPrecisionKillsRelic',
    WeaponKillsPrecisionKillsSideArm = 'WeaponKillsPrecisionKillsSideArm',
    WinLossRatio = 'WinLossRatio',
    UniqueWeaponAssists = 'UniqueWeaponAssists',
    UniqueWeaponAssistDamage = 'UniqueWeaponAssistDamage',
    UniqueWeaponKills = 'UniqueWeaponKills',
    UniqueWeaponPrecisionKills = 'UniqueWeaponPrecisionKills',
    UniqueWeaponKillsPrecisionKills = 'UniqueWeaponKillsPrecisionKills',
    AllParticipantsCount = 'AllParticipantsCount',
    AllParticipantsScore = 'AllParticipantsScore',
    AllParticipantsTimePlayed = 'AllParticipantsTimePlayed',
    ActivityAssists = 'ActivityAssists',
    CompletionReason = 'CompletionReason',
    FireteamId = 'FireteamId',
    LongestKillSpree = 'LongestKillSpree',
    LongestSingleLife = 'LongestSingleLife',
    MostPrecisionKills = 'MostPrecisionKills',
    OrbsDropped = 'OrbsDropped',
    OrbsGathered = 'OrbsGathered',
    StartSeconds = 'StartSeconds',
    TimePlayedSeconds = 'TimePlayedSeconds',
    PlayerCount = 'PlayerCount',
    ActivityPrecisionKills = 'ActivityPrecisionKills',
    PublicEventsCompleted = 'PublicEventsCompleted',
    PublicEventsJoined = 'PublicEventsJoined',
    RemainingTimeAfterQuitSeconds = 'RemainingTimeAfterQuitSeconds',
    TeamScore = 'TeamScore',
    TotalActivityDurationSeconds = 'TotalActivityDurationSeconds',
    DailyMedalsEarned = 'DailyMedalsEarned',
    CombatRating = 'CombatRating',
    LbMostPrecisionKills = 'LbMostPrecisionKills',
    LbLongestKillSpree = 'LbLongestKillSpree',
    LbLongestKillDistance = 'LbLongestKillDistance',
    LbFastestCompletionMs = 'LbFastestCompletionMs',
    LbLongestSingleLife = 'LbLongestSingleLife',
    FastestCompletionMs = 'FastestCompletionMs',
    LongestKillDistance = 'LongestKillDistance',
    HighestCharacterLevel = 'HighestCharacterLevel',
    HighestLightLevel = 'HighestLightLevel',
    HighestSandboxLevel = 'HighestSandboxLevel',
    SparksCaptured = 'SparksCaptured',
    SlamDunks = 'SlamDunks',
    StyleDunks = 'StyleDunks',
    DunkKills = 'DunkKills',
    CarrierKills = 'CarrierKills',
    ActivityGatesHit = 'ActivityGatesHit',
    RaceCompletionSeconds = 'RaceCompletionSeconds',
    GatesHit = 'GatesHit',
    RaceCompletionMilliseconds = 'RaceCompletionMilliseconds',
}
